"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](#282828)\
$os\
[](bg:#B71D49 fg:#282828)\
$directory\
[](bg:#A51583 fg:#B71D49)\
$git_branch\
$git_status\
[](fg:#A51583 bg:#E2A200)\
$git_state\
[](fg:#E2A200 bg:#0087D5)\
$c\
$java\
$nodejs\
$python\
[](fg:#0087D5 bg:#AD9E7F)\
$time\
$status\
"""

# $git_state\ https://starship.rs/config/#git-state
# $docker_context\ https://starship.rs/config/#docker-context

[os]
style = "bg:#282828 fg:#F1F1F1"
format = '[$symbol]($style)'
disabled = false

[os.symbols]
CentOS = " "
Debian = " "
Fedora = " "
Gentoo = " "
Linux = " "
Macos = " "
Raspbian = " "
Redhat = " "
Ubuntu = " "
Windows = " "
Unknown = "? "

[directory]
style = "bg:#B71D49 fg:#F1F1F1"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#A51583 fg:#F1F1F1"
format = '[ $symbol $branch ]($style)'
truncation_length = 10

[git_status]
style = "bg:#A51583 fg:#F1F1F1"
format = '[$all_status$ahead_behind ]($style)'

[git_state]
style = "bg:#E2A200 fg:#F1F1F1"

[c]
symbol = " "
style = "bg:#0087D5 fg:#F1F1F1"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#0087D5 fg:#F1F1F1"
format = '[ $symbol ($version) ]($style)'

[lua]
symbol = ""
style = "bg:#0087D5 fg:#F1F1F1"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "󰎙"
style = "bg:#0087D5 fg:#F1F1F1"
version_format = 'v${major}'
format = '[ $symbol ($version) ]($style)'

[python]
symbol = " "
style = "bg:#0087D5 fg:#F1F1F1"
format = '[ $symbol $context ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#AD9E7F fg:#F1F1F1"
format = '[ $time ]($style)'

[status]
style = 'bg:#AD9E7F fg:#F1F1F1'
symbol = '[](fg:#AD9E7F bg:#A51024)[](fg:#A51024)'
success_symbol = '[](fg:#AD9E7F bg:#038603)[](fg:#038603)'
not_executable_symbol = '[](fg:#AD9E7F bg:#B71D49)[ 󰜺 ](bg:#B71D49)[](fg:#B71D49)'
not_found_symbol = '[](fg:#AD9E7F bg:#A51583)[ ? ](bg:#A51583)[](fg:#A51583)'
sigint_symbol = '[](fg:#AD9E7F bg:#E2A200)[  ](bg:#E2A200)[](fg:#E2A200)'
signal_symbol = '[](fg:#AD9E7F bg:#0087D5)[ 󰙎 ](bg:#0087D5)[](fg:#0087D5)'
format = '$symbol '
map_symbol = true
disabled = false
