"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](#282828)\
[ ](bg:#282828 fg:#F1F1F1)\
[](bg:#B71D49 fg:#282828)\
$directory\
[](bg:#A51583 fg:#B71D49)\
$docker_context\
[](fg:#A51583 bg:#E2A200)\
$git_branch\
$git_status\
[](fg:#E2A200 bg:#0087D5)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#0087D5 bg:#AD9E7F)\
$time\
$status\
"""

[directory]
style = "bg:#B71D49 fg:#F1F1F1"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#E2A200 fg:#F1F1F1"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#E2A200 fg:#F1F1F1"
format = '[$all_status$ahead_behind ]($style)'

[c]
symbol = " "
style = "bg:#0087D5 fg:#F1F1F1"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#0087D5 fg:#F1F1F1"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#0087D5 fg:#F1F1F1"
version_format = 'v${major}'
format = '[ $symbol ($version) ]($style)'

[python]
symbol = " "
style = "bg:#0087D5 fg:#F1F1F1"
format = '[ $symbol $context ]($style)'

[docker_context]
symbol = " "
style = "bg:#A51583 fg:#F1F1F1"
format = '[ $symbol $context ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#AD9E7F fg:#F1F1F1"
format = '[ $time ]($style)'

[status]
style = 'bg:#AD9E7F fg:#F1F1F1'
symbol = '[](fg:#AD9E7F bg:#A51024)[](fg:#A51024)'
success_symbol = '[](fg:#AD9E7F bg:#038603)[](fg:#038603)'
not_executable_symbol = '[](fg:#AD9E7F bg:#A51024)[](fg:#A51024)'
not_found_symbol = '[](fg:#AD9E7F bg:#E2A200)[](fg:#E2A200)'
format = '$symbol '
map_symbol = true
disabled = false
